services:
  - type: web
    name: venue-booking-api
    env: node
    rootDir: venue-booking-api
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.19.5
      - key: CORS_ORIGIN
        value: https://venue-booking-frontend-a3ib.onrender.com
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_iOtv3yJjxY2I@ep-icy-block-adf4etsv-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

  - type: web
    name: venue-booking-frontend
    env: static
    rootDir: venue-booking-frontend
    buildCommand: npm install --include=dev && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://venue-booking-api-rjes.onrender.com
