services:
  - type: web
    name: venue-booking-api
    env: node
    rootDir: venue-booking-api
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start:with-migrate:with-migrate
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 20.19.5
      - key: CORS_ORIGIN
        value: https://venue-booking-frontend-a3ib.onrender.com
      - key: SESSION_SECRET
        generateValue: true
      # 如果你不需要舊的共用密碼，可以直接刪除這個變數，保留更安全
      # - key: ADMIN_PASSWORD
      #   generateValue: true

      # ✅ 每位管理者的帳密（JSON）
      - key: ADMIN_USERS_JSON
        value: |
          {
            "edelbrock": "B123456789o!!",
            "ntchurch": "ntchurch2025!!"
          }

      # 建議加上 REDIS_URL（正式環境）
      # - key: REDIS_URL
      #   value: redis://default:<PASSWORD>@<HOST>:<PORT>

      - key: DATABASE_URL
        value: "<ROTATE_ME_WITH_NEW_NEON_URL>"

  - type: web
    name: venue-booking-frontend
    env: static
    rootDir: venue-booking-frontend
    buildCommand: npm install --include=dev && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://venue-booking-api-rjes.onrender.com
      # - key: VITE_UI_SKIN
      #   value: tailwind